/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCapitalRouteImport } from './routes/_authenticated/capital'
import { Route as AuthenticatedKliyanRouteImport } from './routes/_authenticated/kliyan'
import { Route as AuthenticatedKliyanListRouteImport } from './routes/_authenticated/kliyan-list'
import { Route as AuthenticatedPreListRouteImport } from './routes/_authenticated/pre-list'
import { Route as AuthenticatedSolRouteImport } from './routes/_authenticated/sol'
import { Route as AuthenticatedSolicitudesPreRouteImport } from './routes/_authenticated/solicitudes-pre'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientIdRouteImport } from './routes/_authenticated/admin.$clientId'
import { Route as AuthenticatedResiPaymentIdRouteImport } from './routes/_authenticated/resi.$paymentId'
import { Route as AuthenticatedSolMemberGroupIdMemberIdRouteImport } from './routes/_authenticated/sol-member.$groupId.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCapitalRoute = AuthenticatedCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKliyanRoute = AuthenticatedKliyanRouteImport.update({
  id: '/kliyan',
  path: '/kliyan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKliyanListRoute = AuthenticatedKliyanListRouteImport.update({
  id: '/kliyan-list',
  path: '/kliyan-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreListRoute = AuthenticatedPreListRouteImport.update({
  id: '/pre-list',
  path: '/pre-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolRoute = AuthenticatedSolRouteImport.update({
  id: '/sol',
  path: '/sol',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudesPreRoute =
  AuthenticatedSolicitudesPreRouteImport.update({
    id: '/solicitudes-pre',
    path: '/solicitudes-pre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminClientIdRoute =
  AuthenticatedAdminClientIdRouteImport.update({
    id: '/admin/$clientId',
    path: '/admin/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResiPaymentIdRoute =
  AuthenticatedResiPaymentIdRouteImport.update({
    id: '/resi/$paymentId',
    path: '/resi/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolMemberGroupIdMemberIdRoute =
  AuthenticatedSolMemberGroupIdMemberIdRouteImport.update({
    id: '/sol-member/$groupId/$memberId',
    path: '/sol-member/$groupId/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/kliyan': typeof AuthenticatedKliyanRoute
  '/kliyan-list': typeof AuthenticatedKliyanListRoute
  '/pre-list': typeof AuthenticatedPreListRoute
  '/sol': typeof AuthenticatedSolRoute
  '/solicitudes-pre': typeof AuthenticatedSolicitudesPreRoute
  '/admin/$clientId': typeof AuthenticatedAdminClientIdRoute
  '/resi/$paymentId': typeof AuthenticatedResiPaymentIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/sol-member/$groupId/$memberId': typeof AuthenticatedSolMemberGroupIdMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/kliyan': typeof AuthenticatedKliyanRoute
  '/kliyan-list': typeof AuthenticatedKliyanListRoute
  '/pre-list': typeof AuthenticatedPreListRoute
  '/sol': typeof AuthenticatedSolRoute
  '/solicitudes-pre': typeof AuthenticatedSolicitudesPreRoute
  '/admin/$clientId': typeof AuthenticatedAdminClientIdRoute
  '/resi/$paymentId': typeof AuthenticatedResiPaymentIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/sol-member/$groupId/$memberId': typeof AuthenticatedSolMemberGroupIdMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/capital': typeof AuthenticatedCapitalRoute
  '/_authenticated/kliyan': typeof AuthenticatedKliyanRoute
  '/_authenticated/kliyan-list': typeof AuthenticatedKliyanListRoute
  '/_authenticated/pre-list': typeof AuthenticatedPreListRoute
  '/_authenticated/sol': typeof AuthenticatedSolRoute
  '/_authenticated/solicitudes-pre': typeof AuthenticatedSolicitudesPreRoute
  '/_authenticated/admin/$clientId': typeof AuthenticatedAdminClientIdRoute
  '/_authenticated/resi/$paymentId': typeof AuthenticatedResiPaymentIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/sol-member/$groupId/$memberId': typeof AuthenticatedSolMemberGroupIdMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capital'
    | '/kliyan'
    | '/kliyan-list'
    | '/pre-list'
    | '/sol'
    | '/solicitudes-pre'
    | '/admin/$clientId'
    | '/resi/$paymentId'
    | '/admin/'
    | '/sol-member/$groupId/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capital'
    | '/kliyan'
    | '/kliyan-list'
    | '/pre-list'
    | '/sol'
    | '/solicitudes-pre'
    | '/admin/$clientId'
    | '/resi/$paymentId'
    | '/admin'
    | '/sol-member/$groupId/$memberId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/capital'
    | '/_authenticated/kliyan'
    | '/_authenticated/kliyan-list'
    | '/_authenticated/pre-list'
    | '/_authenticated/sol'
    | '/_authenticated/solicitudes-pre'
    | '/_authenticated/admin/$clientId'
    | '/_authenticated/resi/$paymentId'
    | '/_authenticated/admin/'
    | '/_authenticated/sol-member/$groupId/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capital': {
      id: '/_authenticated/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof AuthenticatedCapitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kliyan': {
      id: '/_authenticated/kliyan'
      path: '/kliyan'
      fullPath: '/kliyan'
      preLoaderRoute: typeof AuthenticatedKliyanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kliyan-list': {
      id: '/_authenticated/kliyan-list'
      path: '/kliyan-list'
      fullPath: '/kliyan-list'
      preLoaderRoute: typeof AuthenticatedKliyanListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-list': {
      id: '/_authenticated/pre-list'
      path: '/pre-list'
      fullPath: '/pre-list'
      preLoaderRoute: typeof AuthenticatedPreListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sol': {
      id: '/_authenticated/sol'
      path: '/sol'
      fullPath: '/sol'
      preLoaderRoute: typeof AuthenticatedSolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes-pre': {
      id: '/_authenticated/solicitudes-pre'
      path: '/solicitudes-pre'
      fullPath: '/solicitudes-pre'
      preLoaderRoute: typeof AuthenticatedSolicitudesPreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$clientId': {
      id: '/_authenticated/admin/$clientId'
      path: '/admin/$clientId'
      fullPath: '/admin/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resi/$paymentId': {
      id: '/_authenticated/resi/$paymentId'
      path: '/resi/$paymentId'
      fullPath: '/resi/$paymentId'
      preLoaderRoute: typeof AuthenticatedResiPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sol-member/$groupId/$memberId': {
      id: '/_authenticated/sol-member/$groupId/$memberId'
      path: '/sol-member/$groupId/$memberId'
      fullPath: '/sol-member/$groupId/$memberId'
      preLoaderRoute: typeof AuthenticatedSolMemberGroupIdMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCapitalRoute: typeof AuthenticatedCapitalRoute
  AuthenticatedKliyanRoute: typeof AuthenticatedKliyanRoute
  AuthenticatedKliyanListRoute: typeof AuthenticatedKliyanListRoute
  AuthenticatedPreListRoute: typeof AuthenticatedPreListRoute
  AuthenticatedSolRoute: typeof AuthenticatedSolRoute
  AuthenticatedSolicitudesPreRoute: typeof AuthenticatedSolicitudesPreRoute
  AuthenticatedAdminClientIdRoute: typeof AuthenticatedAdminClientIdRoute
  AuthenticatedResiPaymentIdRoute: typeof AuthenticatedResiPaymentIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSolMemberGroupIdMemberIdRoute: typeof AuthenticatedSolMemberGroupIdMemberIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCapitalRoute: AuthenticatedCapitalRoute,
  AuthenticatedKliyanRoute: AuthenticatedKliyanRoute,
  AuthenticatedKliyanListRoute: AuthenticatedKliyanListRoute,
  AuthenticatedPreListRoute: AuthenticatedPreListRoute,
  AuthenticatedSolRoute: AuthenticatedSolRoute,
  AuthenticatedSolicitudesPreRoute: AuthenticatedSolicitudesPreRoute,
  AuthenticatedAdminClientIdRoute: AuthenticatedAdminClientIdRoute,
  AuthenticatedResiPaymentIdRoute: AuthenticatedResiPaymentIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSolMemberGroupIdMemberIdRoute:
    AuthenticatedSolMemberGroupIdMemberIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
